### ISSUE TITLE
error while running chioso step1

### ISSUE THREAD

**Issue by shrutikhare-git** [jiyuuchc/chioso#1]
I am trying to run chioso on an Ubuntu machine. What does the following error mean? Is it about h5ad formatting? (I converted from RDS to h5ad)
Could you share the desired format for gene list? I currently have it as a text file with 1 gene name per line.
Thanks!

command - python -m chioso.pp-ref --data data.h5ad --genes gene_list --outdir out

ERROR - 
2024-06-26 18:30:52.066995: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-26 18:30:52.659633: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
I0626 18:30:53.861779 140163648001856 pp-ref.py:32] Read gene names from gene_list
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dglab/software/miniforge/envs/chioso/lib/python3.11/site-packages/chioso/pp-ref.py", line 82, in <module>
    app.run(main)
  File "/home/dglab/software/miniforge/envs/chioso/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/dglab/software/miniforge/envs/chioso/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/dglab/software/miniforge/envs/chioso/lib/python3.11/site-packages/chioso/pp-ref.py", line 78, in main
    process_h5ad()
  File "/home/dglab/software/miniforge/envs/chioso/lib/python3.11/site-packages/chioso/pp-ref.py", line 34, in process_h5ad
    genes = json.load(f)
            ^^^^^^^^^^^^
  File "/home/dglab/software/miniforge/envs/chioso/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/home/dglab/software/miniforge/envs/chioso/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dglab/software/miniforge/envs/chioso/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dglab/software/miniforge/envs/chioso/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jiyuuchc** [comment]
Apologies for the misleading documentation.

The gene_list file should follow JSON format, i.e., it should look like this:

["4930594M17Rik", "Gm2832", "Enpp5", "Gm9837", ....]

**Comment by shrutikhare-git** [comment]
Thanks a lot for your prompt reply. I now have a new error - KeyError: 'celltype'
I guess my object needs to have a column named 'celltype'? (Mine is currently called Broad_CellType. Is there any way to specify that instead?)
TIA.

**Comment by jiyuuchc** [comment]
*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

You can also override in command line:  --col=Broad_CellType

________________________________________

**Comment by shrutikhare-git** [comment]
Hi again, I am currently stuck with this vague error - 'AttributeError: 'numpy.ndarray' object has no attribute 'indices'' - while running step 1. I am using this command on an Ubuntu machine - 'python -m chioso.pp-ref --data /path/object.h5ad --genes /path/gene_list_test --outdir /test --col="Broad_CellType"

I was wondering at which stage do I need to specify the spatial data in space-deliminated text format with four feature columns: gene, x, y, counts? Thanks!

**Comment by jiyuuchc** [comment]
*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

Shruti,

The error is because your h5ad file is created with a dense array instead of sparse array.

The fact that your reference sequencing data can be stored with a dense array indicated that this is a fairy small dataset.

Chioso is created specifically to handle _very_ large datasets, which current tools are having difficulties with. Thus the code assumed that the files were created with sparse arrays.

I've committed a patch to allow dense arrays, so your command should pass now if you update your installation to the head version

However, be warned that you may not find chioso to have any significant advantage if you are dealing with relatively small amount of data.

Regarding your second question: I wonder if you missed the bottom half of the step-1 code block in the README:

python -m chioso.pp-spatial --data <st text file> --genes <gene file> --outdir <outdir>

This can be run independently of the reference data preprocessing. Typically you also run this multiple times, because people tend to save data of multiple samples in different files.

Ji

________________________________________
